# Python Dev - Scripts, Modules and Packages

## Practice exercise answers

### Exercise One: Running Python Code

This isn't the most complicated bit of code, but does use several inbuilt functions, as well as list comprehensions, all of which are very useful to get familar with. A version with the 4th power included looks something like

```python
def square_cube_quartic(n):
    return sorted([i**2 for i in range(n)]+[i**3 for i in range(n)]+[i**4 for i in range(n)])
print(square_cube_quartic(3))
print(square_cube_quartic(10))
```

### Exercise Two: Find the primes

The following code will work (although it isn't the only way to do it)

```python
N = 20
test = 2
primes = []
while len(primes)<N:
    for p in primes:
        if p**2>test:
            primes.append(test)
            break
        if test%p==0:
            break
    # special case
    if len(primes)==0:
        primes.append(test)
    test += 1
print(primes)
```

This version uses the fact that a non-prime must have at least one prime factor smaller than its square root to maximise search efficiency, by using break statements to fail fast. There is a school of thought which feels that this makes code harder to understand.

### Exercise: Find the mean: short version
For the short exercise the following code will work.

```python
import sys
def mean(X):
    return sum(X)/float(len(X))
print(mean([float(x) for x in sys.argv[1:]]))
```
Note that the extra float command in the mean function is just there protection for (the very old) Python 2, where integer division behaves differently from floating point division by default.

### Exercise: Find the mean: version with options parsing
For the version with options parsing, the following code will work.

```python
import argparse

parser = argparse.ArgumentParser()

parser.add_argument("number", nargs='+', help="numbers to take mean of")
parser.add_argument("-b", "--binary", help="numbers are in binary",
                    action="store_true")
parser.add_argument("-o", "--octal", help="numbers are in octal",
                    action="store_true")
parser.add_argument("-x", "--hex", help="numbers are in hexadecimal",
                    action="store_true")
args = parser.parse_args()

if sum([args.hex, args.binary, args.octal]) not in [0, 1]:
    raise ArgumentError

def a2num(x):
    """Transfer string into number."""
    if args.binary:
        return int(x, 2)
    elif args.octal:
        return int(x, 8)
    elif args.hex:
        return int(x, 16)
    return float(x)

def mean(X):
    """ Take mean of X."""
    return sum(X)/float(len(X))

print(mean([a2num(x) for x in args.number]))
```

### Exercise: Plots in scripts

```python
import numpy as np
import matplotlib.pyplot as pyplot

x = np.linspace(0, 2.0*np.pi)

pyplot.plot(x, np.sin(x))
pyplot.plot(x, np.cos(x))
pyplot.plot(x, np.tan(x))

pyplot.axis([0, 2.0*np.pi, -1, 1])
pyplot.show()

pyplot.savefig('fig.png')
pyplot.savefig('fig.pdf')
```

This is the "do everything version. We use the axis command to scale everything so the sine and cosine functions can be seen.

### Exercise: Complex square root
The following code is acceptable. Note that the primary interest here is the documentation

```
def sqrt(x):
    """
    Calculate complex roots of a real input.

    This returns a tuple for all inputs except 0.

    Parameters
    ----------

    x : real
        real number

    Returns
    -------

    tuple or 0.0
        Both complex square roots of x 

    """

    from math import sqrt

    if x is 0.0:
         return 0.0

    surd = sqrt(abs(x))

    if x > 0.0:
        return (-surd, surd)
    else:
        return (-surd*1j, surd*1j)
```

### Exercise: A primes module
```python
""" Module to calculate prime numbers."""

import sys

def find_nth_prime(n, primes=None):
    primes = primes or [2]
    test = primes[-1]+1
    while len(primes)<n:
    	for p in primes:
            if p**2>test:
                primes.append(test)
                break
            if test%p==0:
                break
        # special case
        if len(primes)==0:
            primes.append(test)
        test += 1
    return primes

if __name__=="__main__":
    print(find_nth_prime(int(sys.argv[0])))
```

### Exercise: A primes package
Download and unzip [the following file](https://msc-acse.github.io/ACSE-1/lectures/primes.zip) to obtain an example primes Python package. The prime factors function looks something like the following:
```python
def prime_factors(x, primes=None):
    primes = primes or [2]
    factors = []
    primes = primes_up_to(x, primes)
    while x>1:
        for p in primes:
            while x%p==0:
                factors.append(p)
	        x/=p

    return factors

def primes_up_to(x, primes=None):
    primes = primes or [2]
    test = primes[-1]+1
    while primes[-1]<x:
    	for p in primes:
            if p**2>test:
                primes.append(test)
                break
            if test%p==0:
                break
        # special case
        if len(primes)==0:
            primes.append(test)
	test += 1
    return primes[:-2]
```

### Exercise: Project Euler Problem 1

We could use a for loop, or a list comprehension. In this case, there doesn't seem to be much difference in the timing.

In [37]:
def fun1(n):
    total = 0
    for k in range(1, n):
        if k%3==0 or k%5==0:
            total += k
    return total

def fun2(n):
    return sum([k for k in range(1, n) if k%3==0 or k%5==0])

print(fun1(1000))
print(fun2(1000))

# We'll time with a larger number
%timeit fun1(10000)
%timeit fun2(10000)

233168
233168
5 ms ± 529 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
4.93 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Alternatively, we can try a mathematician's answer. We're looking for the sum of all multiples of 3 under 1000 plus the sum of all multiples of 45 under 1000 minus the sum of all multiples of 15 under 1000 (to remove the double counting). This is
\[3\sum_{i=1}^{333}+5\sum_{i=1}^{199}-15\sum_{i=1}^{66}\]
Now $sum_i^n i = \frac{1}{2}n(n+1)$.



In [45]:
def fun3(n):
    return n*(n+1)//2
%timeit 3*fun3(9999//3)+5*fun3(9999//5)-15*fun3(9999//15)

print(3*fun3(999//3)+5*fun3(999//5)-15*fun3(999//15))

3.18 µs ± 124 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
233168


### Exercise: Project Euler >Problem 5

We can attempt to brute force this answer, but this is a very slow way to do things


In [47]:
# this is really, really slow
test = 21
while not all([test%(k+1)==0 for k in range(20) ]):
    test += 1


It turns out the answer is in primes. We need a number which contains the highest multiple of each prime number present in the set ${1,\ldots, 20}$

so code like

```
primes = primes_up_to(20)
test = 1
for p in primes:
    q = 1
    while q<20:
        q *= p
    test *= p
print(test)
```

will work, in this case generating $16\times9\times5\times7\times11\times13\times17\times\19=




### The Abelian Sandpile

There are several ways of approaching this problem. Conceptually, perhaps the simplest approach for a beginner is to sweep through all the cells, one by one, then topple them if they are too tall. At the end, if you haven't toppled cell then all cells must be stable and you can stop, otherwise start the sweep again. Perhaps, something like.

In [18]:
import numpy as np

def slow_sandpile(initial_state):
    """
    Generate final state for Abelian Sandpile.
    Parameters
    ----------
    initial_state : array_like or list of lists
         Initial 2d state of grid in an array of integers.
    Returns
    -------
    ndarray
         Final state of grid in array of integers.
    """

    state = np.array(initial_state, int)

    flag = True
    while flag:
        flag = False
        for i in range(state.shape[0]):
            for j in range(state.shape[1]):
                if state[i, j]>=4:
                    flag = True # something changed, so we're not finished
                    state[i, j] -= 4
                    if i>0:
                        state[i-1, j] += 1
                    if i<state.shape[0]-1:
                        state[i+1, j] += 1
                    if j>0:
                        state[i, j-1] += 1
                    if j<state.shape[1]-1:
                        state[i, j+1] += 1

    return state

This will end up with the correct answer once it halts, but it is slow, particularly since it uses Python `for` loops for all the iterations. We can do better by leveraging `numpy` to do more work outside our Python loops. One of the faster methods is to update all the unstable sites at once:

In [19]:
import numpy as np

def fast_sandpile(initial_state):
    """
    Generate final state for Abelian Sandpile.
    Parameters
    ----------
    initial_state : array_like or list of lists
         Initial 2d state of grid in an array of integers.
    Returns
    -------
    ndarray
         Final state of grid in array of integers.
    """

    state = np.array(initial_state, int)
    
    print(state)
    
    # Find the sites which are going to topple.
    unstable = 1*(state >= 4)
    
    # Loop until nothing more can topple.
    while (unstable).any():

        # Topple everythin at once
        state -= 4*unstable
        state[0:-1, :] += unstable[1:, :]
        state[1:, :] += unstable[0:-1, :]
        state[:, 0:-1] += unstable[:, 1:]
        state[:, 1:] += unstable[:, 0:-1]
        
        print(state)

        # Update the list of unstable sites for next iteration.
        unstable = 1*(state >= 4)

    return state

In [20]:
import numpy
# Generate random initial state.
X = numpy.random.randint(0, 6, (4, 4))
print(slow_sandpile(X))
print(fast_sandpile(X))
%time Z1 = slow_sandpile(X)
%time Z2 = fast_sandpile(X)

print(f'Z1 equals Z2: {numpy.equal(Z1, Z2).all()}')

[[2 3 3 0]
 [1 3 2 2]
 [1 1 0 2]
 [1 3 2 3]]
[[2 3 3 0]
 [0 2 0 1]
 [4 2 5 3]
 [0 1 3 5]]
[[2 3 3 0]
 [1 2 1 1]
 [0 4 1 5]
 [1 1 5 1]]
[[2 3 3 0]
 [1 3 1 2]
 [1 0 4 1]
 [1 3 1 3]]
[[2 3 3 0]
 [1 3 2 2]
 [1 1 0 2]
 [1 3 2 3]]
[[2 3 3 0]
 [1 3 2 2]
 [1 1 0 2]
 [1 3 2 3]]
Wall time: 0 ns
[[2 3 3 0]
 [0 2 0 1]
 [4 2 5 3]
 [0 1 3 5]]
[[2 3 3 0]
 [1 2 1 1]
 [0 4 1 5]
 [1 1 5 1]]
[[2 3 3 0]
 [1 3 1 2]
 [1 0 4 1]
 [1 3 1 3]]
[[2 3 3 0]
 [1 3 2 2]
 [1 1 0 2]
 [1 3 2 3]]
Wall time: 0 ns
Z1 equals Z2: True
