In [16]:
import json
import numpy as np
import pandas as pd
print(pd.__version__)
a = pd.Series(range(4), ['a', 'b', 'c', 'd'])
print(a.index.tolist())
print(a.index.to_list())

1.1.3
['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd']


# 随机生成测试数据,generate random test data，你不需要运行这一部分you don't need to run this code

In [17]:
# test_data={}
# test_data["lorenz96"]=[];test_data["life"]=[];test_data["life_periodic"]=[];test_data["life_twocolour"]=[];test_data["life_pent"]=[]
# for i in range(0,2):
#     lorenz_array=np.random.randint(0,10,10).tolist()
#     lorenz_nstep=np.random.randint(3,15)
#     test_data["lorenz96"].append((lorenz_array,lorenz_nstep))
    
#     life_mat=np.random.randint(0,2,(4+5*i,4+5*i))
#     life_mat=np.array(life_mat, dtype = bool).tolist()
#     life_nstep=np.random.randint(3,15)
#     test_data["life"].append((life_mat,life_nstep))
    
#     life_periodic_mat=np.random.randint(0,2,(4+5*i,4+5*i))
#     life_periodic_mat=np.array(life_periodic_mat, dtype = bool).tolist()
#     life_periodic_nstep=np.random.randint(3,15)
#     test_data["life_periodic"].append((life_periodic_mat,life_periodic_nstep))
    
#     life_pent_mat=np.random.randint(0,2,(4+5*i,4+5*i))
#     life_pent_mat=np.array(life_pent_mat, dtype = bool).tolist()
#     life_pent_nstep=np.random.randint(3,15)
#     test_data["life_pent"].append((life_pent_mat,life_pent_nstep))
    
#     life_twocolour_mat=np.random.randint(-1,2,(4+5*i,4+5*i)).tolist()
#     life_twocolour_nstep=np.random.randint(3,15)
#     test_data["life_twocolour"].append((life_twocolour_mat,life_twocolour_nstep))

# print(test_data)
# with open("test_data.json",'w') as f:  
#     json.dump(test_data,f)

# 读取测试数据，打印，保存测试结果load test data, print your result,save the test answer

# 注意，将test_data.json与这一ipynb与automata.py放在同级目录 
# note, please place test_data.json and this ipynb in the same file directory with automata.py

In [2]:
import automata
import json
with open("test_data.json") as f:
    test_data=json.load(f)

i_lorenz=0
test_my_answer={}
test_my_answer["lorenz96"]=[];test_my_answer["life"]=[];test_my_answer["life_periodic"]=[];
test_my_answer["life2colour"]=[];test_my_answer["life_pent"]=[]
for test_group in test_data["lorenz96"]:
    initial_state=test_group[0];nstep=test_group[1]
    lorenz_ans=automata.lorenz96(initial_state,nstep)
    print("lorenz96\t%d\n"%i_lorenz);i_lorenz+=1
    print(lorenz_ans);print('\n')
#     test_my_answer["lorenz96"].append(lorenz_ans.tolist())

i_life=0
for test_group in test_data["life"]:
    initial_state=test_group[0];nstep=test_group[1]
    life_ans=automata.life(initial_state,nstep)
    print("life\t%d\n"%i_life);i_life+=1
    print(life_ans);print('\n')
#     test_my_answer["life"].append(life_ans.to_list())

i_life_periodic=0
for test_group in test_data["life_periodic"]:
    initial_state=test_group[0];nstep=test_group[1]
    life_periodic_ans=automata.life_periodic(initial_state,nstep)
    print("life_periodic\t%d\n"%i_life_periodic);i_life_periodic+=1
    print(life_periodic_ans);print('\n')
#     test_my_answer["life_periodic"].append(life_periodic_ans.to_list())

i_life2colour=0
for test_group in test_data["life_twocolour"]:
    initial_state=test_group[0];nstep=test_group[1]
    life2colour_ans=automata.life2colour(initial_state,nstep)
    print("life2colour\t%d\n"%i_life2colour);i_life2colour+=1
    print(life2colour_ans);print('\n')
#     test_my_answer["life2colour"].append(life2colour_ans.tolist())

i_lifepent=0
for test_group in test_data["life_pent"]:
    initial_state=test_group[0];nstep=test_group[1]
    lifepent_ans=automata.lifepent(initial_state,nstep)
    print("lifepent\t%d\n"%i_lifepent);i_lifepent+=1
    print(lifepent_ans);print('\n')
#     test_my_answer["life_pent"].append(lifepent_ans.tolist())
    
with open("gamelife_mytestanswer.json",'w') as f:
    json.dump(test_my_answer,f)

lorenz96	0

[0.44414282568549535, 4.03549206470121, -1.816152557730386, 7.857789036803285, -0.32668623124655216, 7.151788930301021, 7.474833192604699, 5.4740230777343, 2.243014638043073, 6.568105047798739]


lorenz96	1

[1.914652589432299, 8.373750391681476, 6.051998646756656, 5.616329012660949, 7.529628205876191, 7.81782396636763, 7.700555283272901, 7.357477725555684, 7.223694401865812, 4.354683029447403]


life	0

[[0 0 0 0]
 [0 1 1 0]
 [1 0 0 1]
 [0 1 1 0]]


life	1

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


life_periodic	0

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


life_periodic	1

[[0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 0 1 1 0]
 [0 1 0 0 0 0 1 1 0]
 [1 1 0 0 0 0 1 1 0]]


life2colour	0

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# 与别人的测试结果进行比较，修改ground_truth_file变量名
# if you want to compare with the ground result or others' test result ,adjust the variable name ground_truth_file to the name of the file you want to compare with

In [2]:
import numpy as np
#my own test result
my_test_result={};ground_truth={}
my_test_result_file="gamelife_mytestanswer.json"
with open(my_test_result_file) as f:
    my_test_result=json.load(f)


ground_truth_file="ground_truth.json"  #修改这个变量名为你认为的标准答案的json文件名,adjust this file name

with open(ground_truth_file) as f:
    ground_truth=json.load(f)
    
for key1, key2 in zip(my_test_result.keys(), ground_truth.keys()):
    for my_ans,groundtruth_ans in zip(my_test_result[key1],ground_truth[key1]):
        if (np.isclose(my_ans,groundtruth_ans).all()):
            print(key1+"\tsuccessful\n")
        else:
            print(key1+"\twrong\n")
            print("my answer")
            print(my_ans)
            print("ground truth")
            print(groundtruth_ans)
            print('\n')

FileNotFoundError: [Errno 2] No such file or directory: 'gamelife_mytestanswer.json'