## Lecture four "Answers"

This notebook contains example code dealing with the Python in the exercises. Note that the point is the testing, not in the Python

### Exercise One

#### Anagrams

Note this implementation makes the choice to ignore case. It's not particularly efficient (we could fail a lot faster).

In [1]:
def test_anagram(word1, word2):
    """Check if words are anagrams.
    
    
    Parameters
    ----------
    word1: str
       First word
    word2: str
       Second word
       
    Result
    ------
    
    bool
       True if and only if word1 and word2 are anagrams.
    """
    
    return sorted(word1.lower())==sorted(word2.lower())



In [2]:
test_anagram("Carthorse", "Orchestra")

True

In [3]:
test_anagram("cat", "dog")

False

#### Array closest numbers

Again, this version isn't particularly efficient. We certainly double count by generating a matrix of differences. We also make several choices about how to deal with corner cases.


In [4]:
import numpy as np

def closest_elements(array):
    """Find closest elements."""
    
    array = np.asarray(array, np.float64) # convert to floats to be safe

    diff = np.abs(np.subtract.outer(array, array))
    
    diff += np.diag(np.full(len(array), np.inf)) # Set diagonal to infinity
    
    index = np.unravel_index(np.argmin(diff, axis=None), diff.shape)
    
    return array[index[0]], array[index[1]]

In [5]:
closest_elements([1, 3, 4, 9, 100])

(3.0, 4.0)

# Exercise two

### Fizzbuzz

This is very "plain" implementation

In [7]:
def fizzbuzz(x):
    if x%15==0:
        return "fizzbuzz"
    elif x%5==0: 
        return "buzz"
    elif x%3==0:
        return "fizz"
    return x

In [9]:
for x in [9, 60, 4]:
    print(x, fizzbuzz(x))

9 fizz
60 fizzbuzz
4 4


###  Array reordering

For once, this implementation is relatively efficient, since we use numpy for everything.

In [18]:
import numpy as np
def reorder(array):
    d1array = array.ravel()
    d1array.sort()
    return d1array.reshape(array.shape)

In [19]:
X = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print(reorder(X))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Password check

We'll do this the explicit but slow way. The quicker way fo checking would use the regex checking module `re`.

In [20]:
def password_check(password):
    password 
    flag = 8<=len(password)<=1024
    flag = flag and any([str(x) in password for x in range(10)])
    flag = flag and any([x in password for x in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"])
    flag = flag and not any([x in password for x in "@<>!"])
    
    return flag

In [25]:
for x in ("passingWord1",
          "2Short",
          "no_caps"
          "Bad1!!!!!!!!"):
    print(x, password_check(x))

passingWord1 True
2Short False
no_capsBad1!!!!!!!! False
